"""add document table

Revision ID: 0e39102ca17b
Revises: e6ecd5ab66d9
Create Date: 2025-04-25 10:27:25.717998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e39102ca17b'
down_revision: Union[str, None] = 'e6ecd5ab66d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shared_link', sa.String(), nullable=False),
    sa.Column('g_file_id', sa.String(), nullable=False),
    sa.Column('g_folder_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('g_file_id'),
    sa.UniqueConstraint('g_folder_id'),
    sa.UniqueConstraint('user_id', 'g_file_id', name='_user_document_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
