"""add questions

Revision ID: 8c9b4463f684
Revises: 2d994da7efc9
Create Date: 2025-06-13 23:12:05.890604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9b4463f684'
down_revision: Union[str, None] = '2d994da7efc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_questions_id'), 'anonymous_questions', ['id'], unique=False)
    op.create_index(op.f('ix_anonymous_questions_topic'), 'anonymous_questions', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anonymous_questions_topic'), table_name='anonymous_questions')
    op.drop_index(op.f('ix_anonymous_questions_id'), table_name='anonymous_questions')
    op.drop_table('anonymous_questions')
    # ### end Alembic commands ###
