"""edit document folder_id unique field

Revision ID: 918426f880fa
Revises: 0e39102ca17b
Create Date: 2025-04-29 08:35:00.065762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918426f880fa'
down_revision: Union[str, None] = '0e39102ca17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_g_folder_id_key', 'documents', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('documents_g_folder_id_key', 'documents', ['g_folder_id'])
    # ### end Alembic commands ###
