"""add chat statistics table

Revision ID: a739e7d72745
Revises: 8c9b4463f684
Create Date: 2025-06-13 23:28:05.980467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a739e7d72745'
down_revision: Union[str, None] = '8c9b4463f684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email_hash', sa.String(length=64), nullable=True),
    sa.Column('message_length', sa.Integer(), nullable=False),
    sa.Column('message_hash', sa.String(length=64), nullable=True),
    sa.Column('detected_topic', sa.String(length=255), nullable=True),
    sa.Column('is_question', sa.Boolean(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('rag_context_found', sa.Boolean(), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_statistics_id'), 'chat_statistics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_statistics_id'), table_name='chat_statistics')
    op.drop_table('chat_statistics')
    # ### end Alembic commands ###
